"""empty message

Revision ID: cdd106171429
Revises: fedea72c2a6b
Create Date: 2024-05-07 22:36:58.793007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdd106171429'
down_revision = 'fedea72c2a6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dungeon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('acquired', sa.Boolean(), nullable=True),
    sa.Column('icon', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('dungeons')
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dungeon_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'dungeon', ['dungeon_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('dungeon_id')

    op.create_table('dungeons',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('acquired', sa.BOOLEAN(), nullable=True),
    sa.Column('icon', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('dungeon')
    # ### end Alembic commands ###
