name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      FLASK_APP: app
      FLASK_ENV: development
      SECRET_KEY: your_secret_key_here
      DATABASE_URL: sqlite:///instance/eldenring.db

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m venv venv
        . venv/bin/activate
        pip install -r requirements.txt

    - name: Set up instance directory and database
      run: |
        mkdir -p instance
        touch instance/eldenring.db

    - name: Run migrations
      run: |
        . venv/bin/activate
        flask db upgrade

    - name: Run tests
      run: |
        . venv/bin/activate
        pytest
